{% set name = "TSDB" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WenjieDu/TSDB/archive/v{{ version }}.tar.gz
  sha256: e286c392a90c8b49c64e2e8faa3d05376b15a5e26a90e822f0c86b019bddcb9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - tqdm
    - numpy
    - scipy
    - pandas
    - pyarrow
    - requests
    - scikit-learn

test:
  imports:
    - tsdb

about:
  home: https://github.com/WenjieDu/TSDB
  summary: a Python toolbox loads 172 public time series datasets for machine learning/deep learning with a single line of code. Datasets from multiple domains, e.g. healthcare, financial, power, traffic, and weather
  description: |
    Project TSDB is created to help researchers and engineers get rid of data collecting and downloading, 
    and focus back on data processing details. TSDB provides all-in-one-stop convenience for downloading 
    and loading open-source time-series datasets.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://docs.pypots.com/en/latest/tsdb.html
  dev_url: https://github.com/WenjieDu/TSDB

extra:
  recipe-maintainers:
    - WenjieDu
