{% set name = "TSDB" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WenjieDu/TSDB/archive/v{{ version }}.tar.gz
  sha256: ecfdb03eab4eefcce47209f5b04d2ee903fb201e00a586131af7df78459b1c4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - numpy
    - scipy
    - pandas
    - pyarrow
    - requests
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - tsdb

about:
  home: https://github.com/WenjieDu/TSDB
  summary: a Python toolbox loads 172 public time series datasets for machine learning/deep learning with a single line of code. Datasets from multiple domains, e.g. healthcare, financial, power, traffic, and weather
  description: |
    Project TSDB is created to help researchers and engineers get rid of data collecting and downloading, 
    and focus back on data processing details. TSDB provides all-in-one-stop convenience for downloading 
    and loading open-source time-series datasets.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://docs.pypots.com/en/latest/tsdb.html
  dev_url: https://github.com/WenjieDu/TSDB

extra:
  recipe-maintainers:
    - WenjieDu
