{% set name = "TSDB" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WenjieDu/TSDB/archive/v{{ version }}.tar.gz
  sha256: e3b8ae10ff19e1756a6548d44ede9ec36cabadfa0baac46a0ff45e831620dd1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - scikit-learn
    - pandas
    - scipy
    - pyarrow
  run:
    - python >=3.6

test:
  imports:
    - tsdb
  requires:
    - pip
    - numpy
    - scikit-learn
    - pandas
    - scipy
    - pyarrow
  commands:
    - pip check

about:
  home: https://github.com/WenjieDu/TSDB
  summary: a python toolbox helping load time-series datasets easily
  description: |
    Project TSDB is created to help researchers and engineers get rid of data collecting and downloading, 
    and focus back on data processing details. TSDB provides all-in-one-stop convenience for downloading 
    and loading open-source time-series datasets.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://tsdb.readthedocs.io
  dev_url: https://github.com/WenjieDu/TSDB

extra:
  recipe-maintainers:
    - WenjieDu
